### ISSUE TITLE
Emails with , or ; fail to parse correctly and crash  

### ISSUE THREAD

**Issue by hova0** [EWRinc/ServerBackup#2]
Emails in the configuration file with either ; or , fail to split into multiple recipients and crash the service.

Stacktrace:
`Application: ServerBackup.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException
   at System.Net.Mail.MailAddressParser.ParseLocalPart(System.String, Int32 ByRef, Boolean, Boolean)
   at System.Net.Mail.MailAddressParser.ParseAddress(System.String, Boolean, Int32 ByRef)
   at System.Net.Mail.MailAddressParser.ParseMultipleAddresses(System.String)
   at System.Net.Mail.MailAddressCollection.ParseValue(System.String)
   at System.Net.Mail.MailAddressCollection.Add(System.String)
   at System.Net.Mail.Message..ctor(System.String, System.String)
   at System.Net.Mail.MailMessage..ctor(System.String, System.String)
   at System.Net.Mail.SmtpClient.Send(System.String, System.String, System.String, System.String)
   at EWR.ServerBackup.Library.email.Send(System.String, System.String, System.String, System.String)
   at ServerBackup.Scheduler.Scheduler.InternalScheduleLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
`

**Comment by hova0** [comment]
Upon further investigation, only the ; is causing the parsing to crash.    , is apparently the standard way to specify multiple recipients.

**Comment by hova0** [comment]
Fixed with commit d08fda74aa37c3c077ce438484737c08c018f06e
